### ISSUE TITLE
some thoughts about ee-runner

### ISSUE THREAD

**Issue by suredream** [gena/ee-runner#10]
Hi Gena:

I read the code of ee-runner again and want to integrate some features into it:
- including libraries to make the main program short;
- grep the snippets in the terminal to make the coding fast and convenient; 
- extract header comments to generate a snippets/functions index page;
- cookbook, recipe on specific topics

How do you think about these, would you like me to submit a PR to you, or you are ok to let me develop a separate branch?

I made a repo/pages on the following address:

- [https://github.com/suredream/ee-community](https://github.com/suredream/ee-community)
- [https://suredream.github.io/ee-community/](https://suredream.github.io/ee-community/)

Cheers,

**Comment by gena** [comment]
None of these seem to fit the purpose of ee-runner - a simple wrapper around GEE API, allowing to run Playground code.

**Comment by suredream** [comment]
I see. Then I put it as a separate project.
