### ISSUE TITLE
Problems on installing on MacOS X

### ISSUE THREAD

**Issue by alperdincer** [gena/ee-runner#7]
Hi,

I'm trying to install on MacOS X but I got the following errors : 

npm WARN ee-runner@ No repository field.
npm WARN ee-runner@ No license field.
fatal: Not a git repository (or any of the parent directories): .git
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! ee-runner@ init: `npm install && git submodule update --init`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the ee-runner@ init script 'npm install && git submodule update --init'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ee-runner package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && git submodule update --init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ee-runner
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ee-runner
npm ERR! There is likely additional logging output above.

Is there any thing to fix this?

**Comment by gena** [comment]
How did your download it? Not a git repository" means that there is no .git directory found. Try to clone the repository:

> git clone https://github.com/gena/ee-runner

**Comment by alperdincer** [comment]
OK, that solves my problem. As it is stated in the installation part, I downloaded the repo. 

Thanks.

**Comment by gena** [comment]
Thanks! I've updated readme to reflect this. Downloading repository is not an option because of git dependencies.
